name: Github Actions Workflow
run-name: ${{ github.actor }} is building symmetry 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd api
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest

      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
